# MATH 221: Assignment 1
<h3><font color= red>  Due Jan. 19 </font></h3>
<h3> Up to three students may submit the same notebook.  Enter the names of all students who contributed to the assignment on the next line.</h3>
<br><br>

## Names:

<br>

In [1]:
## IMPORTANT!!  Execute this import cell each time before you begin working.
## Before you begin, transfer the laguide.py file from Blackboard to the JupyterHub.

import numpy as np
import laguide as lag

<br><br><br>

### Problem 1a

Under what condition(s) do the three points $(0,y_1)$, $(1,y_2)$, and $(2,y_3)$ lie on a line $y=mx+b$ for some $m$ and $b$?

<h3><font color=blue> Answer 1a </font> </h3>

(*Type your answer here.*)

### Problem 1b

Explain the condition by creating the appropriate linear system and doing the steps of elimination to change the augmented matrix in to a **row-echlon form**.  Do the calcuation by hand and type in the result.  (*Replace the stars with numbers or symbols.*)

<h3><font color=blue> Answer 1b </font> </h3>

Augmented matrix for the linear system:
$$
\begin{equation}
\left[ \begin{array}{rrr}  * & * & *\\  * & * & *  \\ * & * & * \end{array} \right] 
\end{equation}
$$

Row-echelon form of augmented matrix:

$$
\begin{equation}
\left[ \begin{array}{rrr}  * & * & *\\  * & * & *  \\ * & * & * \end{array} \right] 
\end{equation}
$$


### Problem 1c

Let $y_1 = 3.5$, $y_2 = 5.6$, and $y_3 = 7.7$ and calculate $m$ and $b$.

(*Use a code cell to build the appropriate augmented matrix and carry out the row reduction.*)

<h3><font color=blue> Answer 1c </font> </h3>

In [14]:
## CODE HERE



$m = $

$b = $

<br><br><br>

### Problem 2

 Find all vectors $x$ that satisfy the matrix equation $Ax = 0$ where

$$
\begin{equation}
A = \left[ \begin{array}{rrr}  3 & -6 & 0\\  0 & 2 & -2  \\ 1 & -1 & -1 \end{array} \right] 
\end{equation}
$$

(*Create the appropriate augmented matrix and use a code cell to do the steps of elimination.*)

In [7]:
## CODE HERE

A = np.array([[3, -6, 0, 0],[0, 2, -2, 0],[1, -1, -1, 0]])
print(A)
A = lag.RowAdd(A,0,2,-1/3)
print(A)
A = lag.RowReduction(A)
print(A)

[[ 3 -6  0  0]
 [ 0  2 -2  0]
 [ 1 -1 -1  0]]
[[ 3. -6.  0.  0.]
 [ 0.  2. -2.  0.]
 [ 0.  1. -1.  0.]]
Pivot could not be found in column 2 .
[[ 1. -2.  0.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  0.  0.]]


<h3><font color=blue> Answer 2 </font> </h3>


(*Type your answer here.*)

<br><br><br>

### Problem 3
In this problem, you will find examples that demonstrate some of the ways in which algebra with matrices differs from algebra with real numbers.

Find 2$\times$2 matrices that fit the following descriptions.  Show calculations with Python code to verify that your examples work.

<br><br>

Find a matrix $B$ such that $B^2 = -I$, although the entries in $B$ are all real numbers.

<h3><font color=blue> Answer 3a </font> </h3>

In [ ]:
## CODE HERE


Find matrices $C$, $D$, and $E$ such that $CD=CE$, although $C\neq 0$ and $D\neq E$.

<h3><font color=blue> Answer 3b </font> </h3>

In [ ]:
## CODE HERE



Find matrices matrices $F$ and $G$ such that $FG = 0$, although none of the entries in $F$ or $G$ are zero.

<h3><font color=blue> Answer 3c </font> </h3>

In [ ]:
## CODE HERE



<br><br><br>

### Problem 4a

Suppose that $S$ is a square matrix.  Explain why the matrix $P=S+S^T$ must be symmetric and the matrix $Q=S-S^T$ must be skew-symmetric.

<h3><font color=blue> Answer 4a </font> </h3>

(*Type your answer here*.)


### Problem 4b

Compute $P$ and $Q$ when:

$$
\begin{equation}
S = \left[ \begin{array}{rrr}  2 & -3 & 6\\  1 & 0 & -1  \\ 6 & 2 & 2 \end{array} \right] 
\end{equation}
$$

<h3><font color=blue> Answer 4b </font> </h3>

$$
\begin{equation}
P = \left[ \begin{array}{rrr}  * & * & *\\  * & * & *  \\ * & * & * \end{array} \right] 
\end{equation}
$$

$$
\begin{equation}
Q = \left[ \begin{array}{rrr}  * & * & *\\  * & * & *  \\ * & * & * \end{array} \right] 
\end{equation}
$$

<br><br><br>

### Problem 5

If the inverse of $A^2$ is the matrix $B$, show that the inverse of $A$ is the matrix $AB$.

<h3><font color=blue> Answer 5 </font> </h3>

Know $A^2B = I$

and $BA^2 = I$.

Want $ A(AB) = I$

and $(AB)A = I$

(*Type your answer here.*)