# MATH 221: Assignment 2
<h3><font color= red>  Due Feb. 2 </font></h3>
<h3> Up to three students may submit the same notebook.  Enter the names of all students who contributed to the assignment on the next line.</h3>
<br><br>

## Names:

<br>

In [3]:
## IMPORTANT!!  Execute this import cell each time before you begin working.
## Before you begin, transfer the laguide.py file from Blackboard to the JupyterHub.

import numpy as np
import laguide as lag

<br><br><br>

### Problem 1a


Find the $LU$ factorization of $A$ in the case that $v_2 \neq 0$.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr}  
1 & v_1 & 0 & 0 \\  
0 & v_2 & 0 & 0 \\ 
0 & v_3 & 1 & 0 \\ 
0 & v_4 & 0 & 1
\end{array} \right] 
\end{equation}
$$


<h3><font color=blue> Answer 1a </font> </h3>

Do row operations to bring $A$ to $U$.  The entries in $L$ are the negative of the scalars used to create the zeros in the corresponding position in $U$.

$$
\begin{equation}
L = \left[ \begin{array}{rrrr}  
1 & 0 & 0 & 0 \\  
0 & 1 & 0 & 0 \\ 
0 & \frac{v_3}{v_2} & 1 & 0 \\
0 & \frac{v_4}{v_2} & 0 & 1 \\
\end{array} \right]
\quad\quad
U = \left[ \begin{array}{rrrr}  
1 & v_1 & 0 & 0 \\  
0 & v_2 & 0 & 0 \\ 
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{array} \right] 
\end{equation}
$$


### Problem 1b

Find $A^{-1}$ in the case that $v_2 \neq 0$.

$$
\begin{equation}
A = \left[ \begin{array}{rrrr}  
1 & v_1 & 0 & 0 \\  
0 & v_2 & 0 & 0 \\ 
0 & v_3 & 1 & 0 \\ 
0 & v_4 & 0 & 1
\end{array} \right] 
\end{equation}
$$


<h3><font color=blue> Answer 1b </font> </h3>

Starting with the identity $I$, perform the row operations same row operations as are needed to bring $A$ to $I$.

$$
\begin{equation}
A^{-1} = \left[ \begin{array}{rrrr}  
1 & -\frac{v_1}{v_2} & 0 & 0 \\  
0 & \frac{1}{v_2} & 0 & 0 \\ 
0 & -\frac{v_3}{v_2} & 1 & 0 \\
0 & -\frac{v_4}{v_2} & 0 & 1 \\
\end{array} \right] 
\end{equation}
$$


### Problem 1c

Demonstrate that your formulas work when $v_1 = -1$, $v_2 = 2$, $v_3=8$, and $v_4=-3$.

(*Use a code cell to build the matrices and show that $LU=A$ and that $AA^{-1} = I$.*)


<h3><font color=blue> Answer 1c </font> </h3>

In [4]:
## CODE HERE
## Build L, U, A, and Ainverse.  Print L@U and A@Ainverse.

v1,v2,v3,v4 = -1,2,8,-3

A = np.array([[1,v1,0,0],[0,v2,0,0],[0,v3,1,0],[0,v4,0,1]])
print(A)
Ainverse = np.array([[1,-v1/v2,0,0],[0,1/v2,0,0],[0,-v3/v2,1,0],[0,-v4/v2,0,1]])
print(Ainverse)
print(A@Ainverse)
L = np.array([[1,0,0,0],[0,1,0,0],[0,v3/v2,1,0],[0,v4/v2,0,1]])
U = np.array([[1,v1,0,0],[0,v2,0,0],[0,0,1,0],[0,0,0,1]])
print(L)
print(U)
print(L@U)

[[ 1 -1  0  0]
 [ 0  2  0  0]
 [ 0  8  1  0]
 [ 0 -3  0  1]]
[[ 1.   0.5  0.   0. ]
 [ 0.   0.5  0.   0. ]
 [ 0.  -4.   1.   0. ]
 [ 0.   1.5  0.   1. ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.   0. ]
 [ 0.   4.   1.   0. ]
 [ 0.  -1.5  0.   1. ]]
[[ 1 -1  0  0]
 [ 0  2  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]
[[ 1. -1.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  8.  1.  0.]
 [ 0. -3.  0.  1.]]


<br><br><br>

### Problem 2a

Explain why $\det{A^{-1}} = (\det{A})^{-1}$ using only the definition of determinant or the other properties given by Theorems 2.2 and 2.3.

<h3><font color=blue> Answer 2a </font> </h3>

We know that $AA^{-1} = I$ and we know that $\det{(AA^{-1})} = (\det{A})(\det{A^{-1}})$ by **Theorem 2.3.3** and we know that $\det{I} =1$ as part of the definition of determinant.  Putting those facts together we have $(\det{A})(\det{A^{-1}}) = 1$, which means $\det{A^{-1}}=1/(\det{A}) = (\det{A})^{-1}$

<br><br><br>

### Problem 2b

Use your result from Problem 2a and other properties of the determinant to compute $\det{B^{-1}}$.  Do not use a formula for the determinant.

$$
\begin{equation}
B = \left[ \begin{array}{rrrr}  
3 & 2 & 2 & 8 \\  
0 & 6 & -2 & 5 \\ 
0 & 0 & -1 & 0 \\ 
0 & 0 & 0 & 3
\end{array} \right] 
\end{equation}
$$


<h3><font color=blue> Answer 2b </font> </h3>

By **Theorem 2.3.1** $\det{B} = (3)(6)(-1)(3) = -54$.  By **Problem 2a** we have $\det{B^{-1}} = \frac{-1}{54}$.

<br><br><br>

### Problem 3
Find permutation matrices that fit the following descriptions.  **Show calculations with Python code to verify that your examples work.**

<br><br>

Find a $3\times 3$ permutation matrix $P_3$ such that $P_3^3 = I$ but $P_3^k\neq I$ for $k<3$.  

<h3><font color=blue> Answer 3a </font> </h3>

In [5]:
## CODE HERE
## Print P, P@P, and P@P@P
P3 = np.array([[0,1,0],[0,0,1],[1,0,0]])
print(P3)
print('')
print(P3@P3)
print('')
print(P3@P3@P3)

[[0 1 0]
 [0 0 1]
 [1 0 0]]

[[0 0 1]
 [1 0 0]
 [0 1 0]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Find a $5\times 5$ permutation matrix $P_5$ such that $P_5^5 = I$ but $P_5^k\neq I$ for $k<5$.  

<h3><font color=blue> Answer 3b </font> </h3>

In [6]:
## CODE HERE
## Print P, P@P, P@P@P, P@P@P@P, and P@P@P@P@P

P5 = np.array([[0,1,0,0,0],[0,0,0,0,1],[0,0,0,1,0],[1,0,0,0,0],[0,0,1,0,0]])

print(P5)
print('')
print(P5@P5)
print('')
print(P5@P5@P5)
print('')
print(P5@P5@P5@P5)
print('')
print(P5@P5@P5@P5@P5)


[[0 1 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 1 0 0]]

[[0 0 0 0 1]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 0]]

[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]

[[0 0 0 1 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 1 0 0 0]]

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


<br><br><br>

### Problem 4a

Suppose that $n>2$ and $C$ is an $n\times n$ matrix with $[C]_{ij} = i+j$.  Explain why $\det{C} = 0$.  You may do some calculations to see that it is true for a specific value of $n$, but your explanation should not depend on a specific value of $n$.

In [12]:
## The following lines of code create the matrix C.
## Hint: Row operations do not change the value of the determinant.

n = 5
C = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        C[i,j] = i + j
        
print(C)
print('')

B = lag.RowAdd(C,1,2,-1)
B = lag.RowAdd(B,0,1,-1)
print(B)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]

[[0. 1. 2. 3. 4.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


<h3><font color=blue> Answer 4a </font> </h3>

Since the entries $C_{(i+1)j}$ are one more than the entries $C_{ij}$, subtracting a row from the row below it will produce a row of ones.  This can be done with any two rows to create two rows of ones as demonstrated with the calculation above.  These row operations produce a new matrix $B$ with the same determinant as $C$.  The determinant of $B$ (and thus $C$) is zero because the determinant of a matrix with two identical rows is 0 by Theorem 2.2.


<br><br><br>

### Problem 5a

Let $T_n$ be the $n\times n$ **tridiagonal** matrix with 1s along the three central diagonals.  $T_4$ 
is shown here as an example

$$
\begin{equation}
T_4 = \left[ \begin{array}{rrrr}  
1 & 1 & 0 & 0 \\  
1 & 1 & 1 & 0 \\ 
0 & 1 & 1 & 1 \\ 
0 & 0 & 1 & 1 
\end{array} \right] 
\end{equation}
$$

Use the cofactor expansion to show that $\det T_n = \det T_{n-1}- \det T_{n-2}$.

<h3><font color=blue> Answer 5a </font> </h3>


$$
\begin{equation}
T_n = \left[ \begin{array}{rrrrrr}  
    1 & 1 & 0 & \dots & \dots & 0 \\
    1 & 1 & 1 & \ddots & \dots & 0 \\
    0 & 1 & 1 & 1 & \ddots & \vdots \\
    \vdots & \ddots & \ddots & \ddots & \ddots & 0 \\
    \vdots & \vdots & \ddots & 1 & 1 & 1\\
    0 & 0 & \dots & 0 & 1 & 1
\end{array} \right] 
\end{equation}
$$

Write the cofactor expansion for $\det{T_n}$ using the first row.

\begin{equation}
\det{T_n} = t_{11}T_{11} + t_{12}T{12} + \dots
\end{equation}

Only these first two terms are nonzero since $t_{1j}=0$ for $j>2$.  Further $t_{11} = t_{12} = 1$, so we have

\begin{equation}
\det{T_n} = \det{M_{11}} - \det{M_{12}}
\end{equation}

where $M_{11}$ and $M_{12}$ are the minors associated with those entries.  Notice that if we remove the first row and first column from $T_n$ we get $T_{n-1}$, so $M_{11}=T_{n-1}$.

If we eliminate the first row and second column of $T_n$ we get the minor $M_{12}$, which is almost exactly $T_{n-1}$ except that it has a zero in the second row, first column.

$$
\begin{equation}
M_{12} = \left[ \begin{array}{rrrrrr}  
    1 & 1 & 0 & \dots & \dots & 0 \\
    0 & 1 & 1 & \ddots & \dots & 0 \\
    0 & 1 & 1 & 1 & \ddots & \vdots \\
    \vdots & \ddots & \ddots & \ddots & \ddots & 0 \\
    \vdots & \vdots & \ddots & 1 & 1 & 1\\
    0 & 0 & \dots & 0 & 1 & 1
\end{array} \right] 
\end{equation}
$$

We can now expand $\det{M_{12}}$ down the first column and use the fact that the minor associated with the entry in its first row, first column is exactly $T_{n-2}$.

\begin{equation}
\det{M_{12}} = \det{T_{n-2}}
\end{equation}

Substituting this back into the first expansion gives $\det T_n = \det T_{n-1}- \det T_{n-2}$.


### Problem 5b

Use the result of part a to calculate $\det T_{1000}$.


<h3><font color=blue> Answer 5b </font> </h3>

Work out the first two determinants with the cofactor expansion to find that $\det{T_2} = 0$ and $\det{T_3}=-1$.  Now use the formula to work out the first few determinants and look for a pattern.

\begin{eqnarray}
\det{T_4} & = & -1 \\
\det{T_5} & = & 0 \\
\det{T_6} & = & 1 \\
\det{T_7} & = & 1 \\
\det{T_8} & = & 0 \\
\det{T_9} & = & -1 \\
\det{T_{10}} & = & -1 \\
\end{eqnarray}

We see the values cycle through $1, 0, -1, -1, 0, 1, ...$.  Since $1000$ divided by $6$ leaves a remainder of $4$, $T_{1000} = -1$, the fourth number in this repeating set.

*Note the formula $\det T_n = \det T_{n-1}- \det T_{n-2}$ is called a recurrence relation and there are mathematical techniques for solving this relation and finding $T_n$ directly in terms of $n$.*