# MATH 221: Assignment 1
<h3><font color= red>  Due Jan. 19 </font></h3>
<h3> Up to three students may submit the same notebook.  Enter the names of all students who contributed to the assignment on the next line.</h3>
<br><br>

## Names:


<br>

In [1]:
## IMPORTANT!!  Execute this import cell each time before you begin working.
## Before you begin, transfer the laguide.py file from Blackboard to the JupyterHub.

import numpy as np
import laguide as lag

<br><br><br>

### Problem 1a

Under what condition(s) do the three points $(0,y_1)$, $(1,y_2)$, and $(2,y_3)$ lie on a line $y=mx+b$ for some $m$ and $b$?

<h3><font color=blue> Answer 1a </font> </h3>

The slope of a line connecting any two of the points must be the same.

$y_1-2y_2+y_3=0$

### Problem 1b

Explain the condition by creating the appropriate linear system and doing the steps of elimination to change the augmented matrix in to a **row-echlon form**.  Do the calcuation by hand and type in the result.  (*Replace the stars with numbers or symbols.*)

<h3><font color=blue> Answer 1b </font> </h3>

Augmented matrix for the linear system:
$$
\begin{equation}
\left[ \begin{array}{rrr}  0 & 1 & y_1\\  1 & 1 & y_2  \\ 2 & 1 & y_3 \end{array} \right] 
\end{equation}
$$

If $y_1-2y_2+y_3=0$, then the row-echelon form of augmented matrix is
$$
\begin{equation}
\left[ \begin{array}{rrr}  1 & 1 & y_2\\  0 & 1 & y_1  \\ 0 & 0 & y_3-2y_2+y_1 \end{array} \right] 
\end{equation}
$$


If $y_1-2y_2+y_3\neq 0$, then the row-echelon form of augmented matrix is

$$
\begin{equation}
\left[ \begin{array}{rrr}  1 & 1 & y_2\\  0 & 1 & y_1  \\ 0 & 0 & 1 \end{array} \right] 
\end{equation}
$$

and the system is inconsistent since the third row represents the equation $0=1$.

### Problem 1c

Let $y_1 = 3.5$, $y_2 = 5.6$, and $y_3 = 7.7$ and calculate $m$ and $b$.

(*Use a code cell to build the appropriate augmented matrix and carry out the row reduction.*)

<h3><font color=blue> Answer 1c </font> </h3>

In [2]:
## Code your answer here

C = np.array([[0,1,3.5],[1,1,5.6],[2,1,7.7]])
C_reduced = lag.FullRowReduction(C)
print(C_reduced)

[[1.  0.  2.1]
 [0.  1.  3.5]
 [0.  0.  0. ]]


$m = 2.1$

$b = 3.5$

<br><br><br>

### Problem 2

 Find all vectors $x$ that satisfy the matrix equation $Ax = 0$ where

$$
\begin{equation}
A = \left[ \begin{array}{rrr}  3 & -6 & 0\\  0 & 2 & -2  \\ 1 & -1 & -1 \end{array} \right] 
\end{equation}
$$

(*Create the appropriate augmented matrix and use a code cell to do the steps of elimination.*)

In [3]:
## CODE HERE

A = np.array([[3, -6, 0,0],[0, 2, -2,0],[1, -1, -1,0]])
print(A,'\n')
A = lag.RowAdd(A,0,2,-1/3)
print(A,'\n')
A = lag.RowAdd(A,1,2,-1/2)
print(A,'\n')
A = lag.RowAdd(A,1,0,3)
print(A,'\n')
A = lag.RowScale(A,0,1/3)
print(A,'\n')
A = lag.RowScale(A,1,1/2)
print(A,'\n')

[[ 3 -6  0  0]
 [ 0  2 -2  0]
 [ 1 -1 -1  0]] 

[[ 3. -6.  0.  0.]
 [ 0.  2. -2.  0.]
 [ 0.  1. -1.  0.]] 

[[ 3. -6.  0.  0.]
 [ 0.  2. -2.  0.]
 [ 0.  0.  0.  0.]] 

[[ 3.  0. -6.  0.]
 [ 0.  2. -2.  0.]
 [ 0.  0.  0.  0.]] 

[[ 1.  0. -2.  0.]
 [ 0.  2. -2.  0.]
 [ 0.  0.  0.  0.]] 

[[ 1.  0. -2.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  0.  0.]] 



<h3><font color=blue> Answer 2 </font> </h3>

All vectors of the following form, where $t$ is any real number.

$$
\begin{equation}
x = \left[ \begin{array}{r}  2t \\  t\\ t \end{array} \right] 
\end{equation}
$$


<br><br><br>

### Problem 3
In this problem, you will find examples that demonstrate some of the ways in which algebra with matrices differs from algebra with real numbers.

Find 2$\times$2 matrices that fit the following descriptions.  Show calculations with Python code to verify that your examples work.

<br><br>

Find a matrix $B$ such that $B^2 = -I$, although the entries in $B$ are all real numbers.

<h3><font color=blue> Answer 3a </font> </h3>

In [4]:
## CODE HERE

B = np.array([[0,-1],[1,0]])
print(B@B)

[[-1  0]
 [ 0 -1]]


Find matrices $C$, $D$, and $E$ such that $CD=CE$, although $C\neq 0$ and $D\neq E$.

<h3><font color=blue> Answer 3b </font> </h3>

In [8]:
## CODE HERE
C = np.array([[1,0],[1,0]])
D = np.array([[2,3],[4,5]])
E = np.array([[2,3],[8,1]])

print(C@D)
print('')
print(C@E)

[[2 3]
 [2 3]]

[[2 3]
 [2 3]]


Find matrices matrices $F$ and $G$ such that $FG = 0$, although none of the entries in $F$ or $G$ are zero.

<h3><font color=blue> Answer 3c </font> </h3>

In [6]:
## CODE HERE
F = np.array([[1,-1],[1,-1]])
G = np.array([[2,2],[2,2]])

print(F@G)

[[0 0]
 [0 0]]


<br><br><br>

### Problem 4a

Suppose that $S$ is a square matrix.  Explain why the matrix $P=S+S^T$ must be symmetric and the matrix $Q=S-S^T$ must be skew-symmetric.

<h3><font color=blue> Answer 4a </font> </h3>

$[P]_{ij} = [S]_{ij}+[S^T]_{ij} = [S]_{ij}+[S]_{ji}$ and $[P]_{ji} = [S]_{ji}+[S^T]_{ji} = [S]_{ji}+[S]_{ij} $ so $[P]_{ij} = [P]_{ji}$

Similarly, $[Q]_{ij} = [S]_{ij}-[S]_{ji}$ and $[Q]_{ji} = [S]_{ji}-[S]_{ij}$ so $[Q]_{ij} = -[Q]_{ji}$

OR

$P^T = (S+S^T)^T = S^T+(S^T)^T = S^T + S = P$

$Q^T = (S-S^T)^T = S^T(S^T)^T = S^T - S = -P$



### Problem 4b

Compute $P$ and $Q$ when:

$$
\begin{equation}
S = \left[ \begin{array}{rrr}  2 & -3 & 6\\  1 & 0 & -1  \\ 6 & 2 & 2 \end{array} \right] 
\end{equation}
$$

In [7]:
S = np.array([[2,-3,6],[1,0,-1],[6,2,2]])
print(S)
print('')
print(S+S.T)
print('')
print(S-S.T)

[[ 2 -3  6]
 [ 1  0 -1]
 [ 6  2  2]]

[[ 4 -2 12]
 [-2  0  1]
 [12  1  4]]

[[ 0 -4  0]
 [ 4  0 -3]
 [ 0  3  0]]


<h3><font color=blue> Answer 4b </font> </h3>

$$
\begin{equation}
P = \left[ \begin{array}{rrr}  4 & -2 & 12\\  -2 & 0 & 1  \\ 12 & 1 & 4 \end{array} \right] 
\end{equation}
$$

$$
\begin{equation}
Q = \left[ \begin{array}{rrr}  0 & 4 & 0\\  -4 & 0 & 3  \\ 0 & -3 & 0 \end{array} \right] 
\end{equation}
$$

<br><br><br>

### Problem 5

If the inverse of $A^2$ is the matrix $B$, show that the inverse of $A$ is the matrix $AB$.

<h3><font color=blue> Answer 5 </font> </h3>

Assume that the inverse of $A^2$ is the matrix $B$.  Then we know by the definition of inverse matrices that $A^2B=I$ and that $BA^2=I$.

To show that the inverse of $A$ is $AB$ we need to show that $A(AB) = I$ and that $(AB)A = I$.

1. $A(AB) = A^2B = I$ by the associative property of matrix multiplication and the assumption.

2. $(AB)A = ABAI = ABA(A^2B) = A(BA^2)AB = AIAB = A^2B = I$ using the assumptions and properties of matrix multiplication.
